{
  "GSD": {
    "alias": "CVE-2021-3859",
    "description": "A flaw was found in Undertow that tripped the client-side invocation timeout with certain calls made over HTTP2. This flaw allows an attacker to carry out denial of service attacks.",
    "id": "GSD-2021-3859",
    "references": [
      "https://access.redhat.com/errata/RHSA-2022:0448",
      "https://access.redhat.com/errata/RHSA-2022:0447",
      "https://access.redhat.com/errata/RHSA-2022:0415",
      "https://access.redhat.com/errata/RHSA-2022:0410",
      "https://access.redhat.com/errata/RHSA-2022:0409",
      "https://access.redhat.com/errata/RHSA-2022:0408",
      "https://access.redhat.com/errata/RHSA-2022:0407",
      "https://access.redhat.com/errata/RHSA-2022:0406",
      "https://access.redhat.com/errata/RHSA-2022:0405",
      "https://access.redhat.com/errata/RHSA-2022:0404",
      "https://access.redhat.com/errata/RHSA-2022:0401",
      "https://access.redhat.com/errata/RHSA-2022:0400",
      "https://access.redhat.com/errata/RHSA-2022:1179",
      "https://access.redhat.com/errata/RHSA-2022:5532"
    ]
  },
  "gsd": {
    "metadata": {
      "exploitCode": "unknown",
      "remediation": "unknown",
      "reportConfidence": "confirmed",
      "type": "vulnerability"
    },
    "osvSchema": {
      "aliases": [
        "CVE-2021-3859"
      ],
      "details": "A flaw was found in Undertow that tripped the client-side invocation timeout with certain calls made over HTTP2. This flaw allows an attacker to carry out denial of service attacks.",
      "id": "GSD-2021-3859",
      "modified": "2023-12-13T01:23:34.125594Z",
      "schema_version": "1.4.0"
    }
  },
  "namespaces": {
    "cve.org": {
      "CVE_data_meta": {
        "ASSIGNER": "secalert@redhat.com",
        "ID": "CVE-2021-3859",
        "STATE": "PUBLIC"
      },
      "affects": {
        "vendor": {
          "vendor_data": [
            {
              "product": {
                "product_data": [
                  {
                    "product_name": "undertow",
                    "version": {
                      "version_data": [
                        {
                          "version_affected": "=",
                          "version_value": "Fixed in 2.2.15.Final"
                        }
                      ]
                    }
                  }
                ]
              },
              "vendor_name": "n/a"
            }
          ]
        }
      },
      "data_format": "MITRE",
      "data_type": "CVE",
      "data_version": "4.0",
      "description": {
        "description_data": [
          {
            "lang": "eng",
            "value": "A flaw was found in Undertow that tripped the client-side invocation timeout with certain calls made over HTTP2. This flaw allows an attacker to carry out denial of service attacks."
          }
        ]
      },
      "problemtype": {
        "problemtype_data": [
          {
            "description": [
              {
                "cweId": "CWE-214",
                "lang": "eng",
                "value": "CWE-214 - Invocation of Process Using Visible Sensitive Information"
              }
            ]
          }
        ]
      },
      "references": {
        "reference_data": [
          {
            "name": "https://bugzilla.redhat.com/show_bug.cgi?id=2010378",
            "refsource": "MISC",
            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2010378"
          },
          {
            "name": "https://issues.redhat.com/browse/UNDERTOW-1979",
            "refsource": "MISC",
            "url": "https://issues.redhat.com/browse/UNDERTOW-1979"
          },
          {
            "name": "https://github.com/undertow-io/undertow/pull/1296",
            "refsource": "MISC",
            "url": "https://github.com/undertow-io/undertow/pull/1296"
          },
          {
            "name": "https://github.com/undertow-io/undertow/commit/e43f0ada3f4da6e8579e0020cec3cb1a81e487c2",
            "refsource": "MISC",
            "url": "https://github.com/undertow-io/undertow/commit/e43f0ada3f4da6e8579e0020cec3cb1a81e487c2"
          },
          {
            "name": "https://access.redhat.com/security/cve/CVE-2021-3859",
            "refsource": "MISC",
            "url": "https://access.redhat.com/security/cve/CVE-2021-3859"
          },
          {
            "name": "https://security.netapp.com/advisory/ntap-20221201-0004/",
            "refsource": "MISC",
            "url": "https://security.netapp.com/advisory/ntap-20221201-0004/"
          }
        ]
      }
    },
    "gitlab.com": {
      "advisories": [
        {
          "affected_range": "(,2.2.15)",
          "affected_versions": "All versions before 2.2.15",
          "cvss_v3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "cwe_ids": [
            "CWE-1035",
            "CWE-214",
            "CWE-937"
          ],
          "date": "2022-12-13",
          "description": "A flaw was found in Undertow that tripped the client-side invocation timeout with certain calls made over HTTP2. This flaw allows an attacker to carry out denial of service attacks.",
          "fixed_versions": [
            "2.2.15"
          ],
          "identifier": "CVE-2021-3859",
          "identifiers": [
            "CVE-2021-3859",
            "GHSA-339q-62wm-c39w",
            "GMS-2022-2963"
          ],
          "not_impacted": "",
          "package_slug": "maven/io.undertow/undertow-core",
          "pubdate": "2022-08-26",
          "solution": "Upgrade to version 2.2.15 or above.",
          "title": "Exposure of Resource to Wrong Sphere",
          "urls": [
            "https://nvd.nist.gov/vuln/detail/CVE-2021-3859",
            "https://issues.redhat.com/browse/UNDERTOW-1979",
            "https://github.com/undertow-io/undertow/commit/e43f0ada3f4da6e8579e0020cec3cb1a81e487c2",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2010378",
            "https://access.redhat.com/security/cve/CVE-2021-3859",
            "https://github.com/undertow-io/undertow/pull/1296",
            "https://github.com/undertow-io/undertow/commit/db0f5be43f8e2a4b88fbedd2eb6d5a95a29ceaa8",
            "https://access.redhat.com/security/cve/cve-2021-3859",
            "https://github.com/advisories/GHSA-339q-62wm-c39w"
          ],
          "uuid": "e5739fad-6abf-422f-8c8c-fbd28742dcc9"
        },
        {
          "affected_range": "(,0)",
          "affected_versions": "All versions before 2.2.15",
          "cwe_ids": [
            "CWE-1035",
            "CWE-937"
          ],
          "date": "2022-07-15",
          "description": "Undertow client side invocation timeout raised when calling over HTTP2, this vulnerability can allow attacker to carry out denial of service (DoS) attacks in versions less than 2.2.15 Final.",
          "fixed_versions": [
            "2.2.15"
          ],
          "identifier": "GMS-2022-2963",
          "identifiers": [
            "GHSA-339q-62wm-c39w",
            "GMS-2022-2963",
            "CVE-2021-3859"
          ],
          "not_impacted": "All versions starting from 2.2.15",
          "package_slug": "maven/io.undertow/undertow-core",
          "pubdate": "2022-07-15",
          "solution": "Upgrade to version 2.2.15 or above.",
          "title": "Duplicate of ./maven/io.undertow/undertow-core/CVE-2021-3859.yml",
          "urls": [
            "https://nvd.nist.gov/vuln/detail/CVE-2021-3859",
            "https://github.com/undertow-io/undertow/commit/db0f5be43f8e2a4b88fbedd2eb6d5a95a29ceaa8",
            "https://access.redhat.com/security/cve/cve-2021-3859",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2010378",
            "https://github.com/advisories/GHSA-339q-62wm-c39w"
          ],
          "uuid": "f056d02e-b9e3-4d3a-924f-92302f18de36"
        }
      ]
    },
    "nvd.nist.gov": {
      "configurations": {
        "CVE_data_version": "4.0",
        "nodes": [
          {
            "children": [],
            "cpe_match": [
              {
                "cpe23Uri": "cpe:2.3:a:redhat:jboss_enterprise_application_platform:7.3:*:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": true
              },
              {
                "cpe23Uri": "cpe:2.3:a:redhat:jboss_enterprise_application_platform:7.4:*:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": true
              },
              {
                "cpe23Uri": "cpe:2.3:a:redhat:undertow:*:*:*:*:*:*:*:*",
                "cpe_name": [],
                "versionEndExcluding": "2.2.15",
                "vulnerable": true
              },
              {
                "cpe23Uri": "cpe:2.3:a:redhat:single_sign-on:7.5.1:*:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": true
              },
              {
                "cpe23Uri": "cpe:2.3:a:redhat:single_sign-on:7.4.10:*:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": true
              }
            ],
            "operator": "OR"
          },
          {
            "children": [],
            "cpe_match": [
              {
                "cpe23Uri": "cpe:2.3:a:netapp:oncommand_workflow_automation:-:*:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": true
              },
              {
                "cpe23Uri": "cpe:2.3:a:netapp:oncommand_insight:-:*:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": true
              },
              {
                "cpe23Uri": "cpe:2.3:a:netapp:cloud_secure_agent:-:*:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": true
              }
            ],
            "operator": "OR"
          }
        ]
      },
      "cve": {
        "CVE_data_meta": {
          "ASSIGNER": "secalert@redhat.com",
          "ID": "CVE-2021-3859"
        },
        "data_format": "MITRE",
        "data_type": "CVE",
        "data_version": "4.0",
        "description": {
          "description_data": [
            {
              "lang": "en",
              "value": "A flaw was found in Undertow that tripped the client-side invocation timeout with certain calls made over HTTP2. This flaw allows an attacker to carry out denial of service attacks."
            }
          ]
        },
        "problemtype": {
          "problemtype_data": [
            {
              "description": [
                {
                  "lang": "en",
                  "value": "CWE-214"
                }
              ]
            }
          ]
        },
        "references": {
          "reference_data": [
            {
              "name": "https://issues.redhat.com/browse/UNDERTOW-1979",
              "refsource": "MISC",
              "tags": [
                "Issue Tracking",
                "Patch",
                "Vendor Advisory"
              ],
              "url": "https://issues.redhat.com/browse/UNDERTOW-1979"
            },
            {
              "name": "https://github.com/undertow-io/undertow/commit/e43f0ada3f4da6e8579e0020cec3cb1a81e487c2",
              "refsource": "MISC",
              "tags": [
                "Patch",
                "Third Party Advisory"
              ],
              "url": "https://github.com/undertow-io/undertow/commit/e43f0ada3f4da6e8579e0020cec3cb1a81e487c2"
            },
            {
              "name": "https://bugzilla.redhat.com/show_bug.cgi?id=2010378",
              "refsource": "MISC",
              "tags": [
                "Issue Tracking",
                "Vendor Advisory"
              ],
              "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2010378"
            },
            {
              "name": "https://access.redhat.com/security/cve/CVE-2021-3859",
              "refsource": "MISC",
              "tags": [
                "Vendor Advisory"
              ],
              "url": "https://access.redhat.com/security/cve/CVE-2021-3859"
            },
            {
              "name": "https://github.com/undertow-io/undertow/pull/1296",
              "refsource": "MISC",
              "tags": [
                "Third Party Advisory"
              ],
              "url": "https://github.com/undertow-io/undertow/pull/1296"
            },
            {
              "name": "https://security.netapp.com/advisory/ntap-20221201-0004/",
              "refsource": "CONFIRM",
              "tags": [
                "Third Party Advisory"
              ],
              "url": "https://security.netapp.com/advisory/ntap-20221201-0004/"
            }
          ]
        }
      },
      "impact": {
        "baseMetricV3": {
          "cvssV3": {
            "attackComplexity": "LOW",
            "attackVector": "NETWORK",
            "availabilityImpact": "HIGH",
            "baseScore": 7.5,
            "baseSeverity": "HIGH",
            "confidentialityImpact": "NONE",
            "integrityImpact": "NONE",
            "privilegesRequired": "NONE",
            "scope": "UNCHANGED",
            "userInteraction": "NONE",
            "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "version": "3.1"
          },
          "exploitabilityScore": 3.9,
          "impactScore": 3.6
        }
      },
      "lastModifiedDate": "2022-12-13T02:25Z",
      "publishedDate": "2022-08-26T16:15Z"
    }
  }
}