{
  "GSD": {
    "alias": "CVE-2019-6446",
    "description": "** DISPUTED **   An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources.",
    "id": "GSD-2019-6446",
    "references": [
      "https://www.suse.com/security/cve/CVE-2019-6446.html",
      "https://access.redhat.com/errata/RHSA-2019:3704",
      "https://access.redhat.com/errata/RHSA-2019:3335",
      "https://advisories.mageia.org/CVE-2019-6446.html",
      "https://linux.oracle.com/cve/CVE-2019-6446.html"
    ]
  },
  "gsd": {
    "metadata": {
      "exploitCode": "unknown",
      "remediation": "unknown",
      "reportConfidence": "confirmed",
      "type": "vulnerability"
    },
    "osvSchema": {
      "aliases": [
        "CVE-2019-6446"
      ],
      "details": "** DISPUTED **   An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources.",
      "id": "GSD-2019-6446",
      "modified": "2023-12-13T01:23:48.849317Z",
      "schema_version": "1.4.0"
    }
  },
  "namespaces": {
    "cve.org": {
      "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2019-6446",
        "STATE": "PUBLIC"
      },
      "affects": {
        "vendor": {
          "vendor_data": [
            {
              "product": {
                "product_data": [
                  {
                    "product_name": "n/a",
                    "version": {
                      "version_data": [
                        {
                          "version_value": "n/a"
                        }
                      ]
                    }
                  }
                ]
              },
              "vendor_name": "n/a"
            }
          ]
        }
      },
      "data_format": "MITRE",
      "data_type": "CVE",
      "data_version": "4.0",
      "description": {
        "description_data": [
          {
            "lang": "eng",
            "value": "** DISPUTED **   An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources."
          }
        ]
      },
      "problemtype": {
        "problemtype_data": [
          {
            "description": [
              {
                "lang": "eng",
                "value": "n/a"
              }
            ]
          }
        ]
      },
      "references": {
        "reference_data": [
          {
            "name": "https://bugzilla.suse.com/show_bug.cgi?id=1122208",
            "refsource": "MISC",
            "url": "https://bugzilla.suse.com/show_bug.cgi?id=1122208"
          },
          {
            "name": "106670",
            "refsource": "BID",
            "url": "http://www.securityfocus.com/bid/106670"
          },
          {
            "name": "https://github.com/numpy/numpy/issues/12759",
            "refsource": "MISC",
            "url": "https://github.com/numpy/numpy/issues/12759"
          },
          {
            "name": "FEDORA-2019-1dfe95a864",
            "refsource": "FEDORA",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4/"
          },
          {
            "name": "openSUSE-SU-2019:2227",
            "refsource": "SUSE",
            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html"
          },
          {
            "name": "openSUSE-SU-2019:2225",
            "refsource": "SUSE",
            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html"
          },
          {
            "name": "openSUSE-SU-2019:2259",
            "refsource": "SUSE",
            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html"
          },
          {
            "name": "RHSA-2019:3335",
            "refsource": "REDHAT",
            "url": "https://access.redhat.com/errata/RHSA-2019:3335"
          },
          {
            "name": "RHSA-2019:3704",
            "refsource": "REDHAT",
            "url": "https://access.redhat.com/errata/RHSA-2019:3704"
          }
        ]
      }
    },
    "gitlab.com": {
      "advisories": [
        {
          "affected_range": "<1.16.3",
          "affected_versions": "All versions before 1.16.3",
          "credit": "nanshihui",
          "cvss_v2": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
          "cvss_v3": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
          "cwe_ids": [
            "CWE-1035",
            "CWE-502",
            "CWE-937"
          ],
          "date": "2019-09-30",
          "description": "An unsafe use of the pickle Python module allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a `numpy.load` call. NOTE: third parties dispute this issue because it is a behavior that might have legitimate applications in (for example) loading serialized Python object arrays from trusted and authenticated sources.",
          "fixed_versions": [
            "1.16.3"
          ],
          "identifier": "CVE-2019-6446",
          "identifiers": [
            "CVE-2019-6446"
          ],
          "package_slug": "pypi/numpy",
          "pubdate": "2019-01-16",
          "solution": "Upgrade to version 1.16.3 or above",
          "title": "Arbitrary Code Execution",
          "urls": [
            "http://www.securityfocus.com/bid/106670",
            "https://bugzilla.suse.com/show_bug.cgi?id=1122208",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-6446",
            "https://cwe.mitre.org/data/definitions/94.html",
            "https://github.com/numpy/numpy/issues/12759"
          ],
          "uuid": "b8804275-0868-45f4-9ab6-bfd68ad34e00"
        }
      ]
    },
    "nvd.nist.gov": {
      "cve": {
        "configurations": [
          {
            "nodes": [
              {
                "cpeMatch": [
                  {
                    "criteria": "cpe:2.3:a:numpy:numpy:*:*:*:*:*:*:*:*",
                    "matchCriteriaId": "80912416-97D8-4FF8-B2DB-D587EFC9D4BE",
                    "versionEndIncluding": "1.16.0",
                    "vulnerable": true
                  }
                ],
                "negate": false,
                "operator": "OR"
              }
            ]
          },
          {
            "nodes": [
              {
                "cpeMatch": [
                  {
                    "criteria": "cpe:2.3:o:fedoraproject:fedora:30:*:*:*:*:*:*:*",
                    "matchCriteriaId": "97A4B8DF-58DA-4AB6-A1F9-331B36409BA3",
                    "vulnerable": true
                  }
                ],
                "negate": false,
                "operator": "OR"
              }
            ]
          }
        ],
        "descriptions": [
          {
            "lang": "en",
            "value": "An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources"
          },
          {
            "lang": "es",
            "value": "** EN DISPUTA ** Se ha descubierto un problema en NumPy, en versiones 1.16.0 y anteriores. Emplea el m\u00f3dulo de Python pickle de forma insegura, lo que permite que los atacantes remotos ejecuten c\u00f3digo arbitrario mediante un objeto serializado, tal y como queda demostrado con una llamada numpy.load. NOTA: hay terceros que discuten este problema, ya que es un comportamiento que podr\u00eda tener aplicaciones leg\u00edtimas en, por ejemplo, la carga de arrays de objetos de Python serializados de fuentes fiables y autenticadas."
          }
        ],
        "id": "CVE-2019-6446",
        "lastModified": "2024-04-11T01:05:59.060",
        "metrics": {
          "cvssMetricV2": [
            {
              "acInsufInfo": false,
              "baseSeverity": "HIGH",
              "cvssData": {
                "accessComplexity": "LOW",
                "accessVector": "NETWORK",
                "authentication": "NONE",
                "availabilityImpact": "PARTIAL",
                "baseScore": 7.5,
                "confidentialityImpact": "PARTIAL",
                "integrityImpact": "PARTIAL",
                "vectorString": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
                "version": "2.0"
              },
              "exploitabilityScore": 10.0,
              "impactScore": 6.4,
              "obtainAllPrivilege": false,
              "obtainOtherPrivilege": false,
              "obtainUserPrivilege": false,
              "source": "nvd@nist.gov",
              "type": "Primary",
              "userInteractionRequired": false
            }
          ],
          "cvssMetricV30": [
            {
              "cvssData": {
                "attackComplexity": "LOW",
                "attackVector": "NETWORK",
                "availabilityImpact": "HIGH",
                "baseScore": 9.8,
                "baseSeverity": "CRITICAL",
                "confidentialityImpact": "HIGH",
                "integrityImpact": "HIGH",
                "privilegesRequired": "NONE",
                "scope": "UNCHANGED",
                "userInteraction": "NONE",
                "vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "version": "3.0"
              },
              "exploitabilityScore": 3.9,
              "impactScore": 5.9,
              "source": "nvd@nist.gov",
              "type": "Primary"
            }
          ]
        },
        "published": "2019-01-16T05:29:01.370",
        "references": [
          {
            "source": "cve@mitre.org",
            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html"
          },
          {
            "source": "cve@mitre.org",
            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html"
          },
          {
            "source": "cve@mitre.org",
            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html"
          },
          {
            "source": "cve@mitre.org",
            "tags": [
              "Third Party Advisory",
              "VDB Entry"
            ],
            "url": "http://www.securityfocus.com/bid/106670"
          },
          {
            "source": "cve@mitre.org",
            "url": "https://access.redhat.com/errata/RHSA-2019:3335"
          },
          {
            "source": "cve@mitre.org",
            "url": "https://access.redhat.com/errata/RHSA-2019:3704"
          },
          {
            "source": "cve@mitre.org",
            "tags": [
              "Exploit",
              "Issue Tracking",
              "Third Party Advisory"
            ],
            "url": "https://bugzilla.suse.com/show_bug.cgi?id=1122208"
          },
          {
            "source": "cve@mitre.org",
            "tags": [
              "Exploit",
              "Issue Tracking",
              "Third Party Advisory"
            ],
            "url": "https://github.com/numpy/numpy/issues/12759"
          },
          {
            "source": "cve@mitre.org",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4/"
          }
        ],
        "sourceIdentifier": "cve@mitre.org",
        "vulnStatus": "Modified",
        "weaknesses": [
          {
            "description": [
              {
                "lang": "en",
                "value": "CWE-502"
              }
            ],
            "source": "nvd@nist.gov",
            "type": "Primary"
          }
        ]
      }
    }
  }
}