{
  "GSD": {
    "alias": "CVE-2022-35997",
    "description": "TensorFlow is an open source platform for machine learning. If `tf.sparse.cross` receives an input `separator` that is not a scalar, it gives a `CHECK` fail that can be used to trigger a denial of service attack. We have patched the issue in GitHub commit 83dcb4dbfa094e33db084e97c4d0531a559e0ebf. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue.",
    "id": "GSD-2022-35997",
    "references": [
      "https://www.suse.com/security/cve/CVE-2022-35997.html"
    ]
  },
  "gsd": {
    "metadata": {
      "exploitCode": "unknown",
      "remediation": "unknown",
      "reportConfidence": "confirmed",
      "type": "vulnerability"
    },
    "osvSchema": {
      "aliases": [
        "CVE-2022-35997"
      ],
      "details": "TensorFlow is an open source platform for machine learning. If `tf.sparse.cross` receives an input `separator` that is not a scalar, it gives a `CHECK` fail that can be used to trigger a denial of service attack. We have patched the issue in GitHub commit 83dcb4dbfa094e33db084e97c4d0531a559e0ebf. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue.",
      "id": "GSD-2022-35997",
      "modified": "2023-12-13T01:19:33.322157Z",
      "schema_version": "1.4.0"
    }
  },
  "namespaces": {
    "cve.org": {
      "CVE_data_meta": {
        "ASSIGNER": "security-advisories@github.com",
        "ID": "CVE-2022-35997",
        "STATE": "PUBLIC",
        "TITLE": "`CHECK` fail in `tf.sparse.cross` in TensorFlow"
      },
      "affects": {
        "vendor": {
          "vendor_data": [
            {
              "product": {
                "product_data": [
                  {
                    "product_name": "tensorflow",
                    "version": {
                      "version_data": [
                        {
                          "version_value": "< 2.7.2"
                        },
                        {
                          "version_value": ">= 2.8.0, < 2.8.1"
                        },
                        {
                          "version_value": ">= 2.9.0, < 2.9.1"
                        }
                      ]
                    }
                  }
                ]
              },
              "vendor_name": "tensorflow"
            }
          ]
        }
      },
      "data_format": "MITRE",
      "data_type": "CVE",
      "data_version": "4.0",
      "description": {
        "description_data": [
          {
            "lang": "eng",
            "value": "TensorFlow is an open source platform for machine learning. If `tf.sparse.cross` receives an input `separator` that is not a scalar, it gives a `CHECK` fail that can be used to trigger a denial of service attack. We have patched the issue in GitHub commit 83dcb4dbfa094e33db084e97c4d0531a559e0ebf. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue."
          }
        ]
      },
      "impact": {
        "cvss": {
          "attackComplexity": "HIGH",
          "attackVector": "NETWORK",
          "availabilityImpact": "HIGH",
          "baseScore": 5.9,
          "baseSeverity": "MEDIUM",
          "confidentialityImpact": "NONE",
          "integrityImpact": "NONE",
          "privilegesRequired": "NONE",
          "scope": "UNCHANGED",
          "userInteraction": "NONE",
          "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "version": "3.1"
        }
      },
      "problemtype": {
        "problemtype_data": [
          {
            "description": [
              {
                "lang": "eng",
                "value": "CWE-617: Reachable Assertion"
              }
            ]
          }
        ]
      },
      "references": {
        "reference_data": [
          {
            "name": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p7hr-f446-x6qf",
            "refsource": "CONFIRM",
            "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p7hr-f446-x6qf"
          },
          {
            "name": "https://github.com/tensorflow/tensorflow/commit/83dcb4dbfa094e33db084e97c4d0531a559e0ebf",
            "refsource": "MISC",
            "url": "https://github.com/tensorflow/tensorflow/commit/83dcb4dbfa094e33db084e97c4d0531a559e0ebf"
          }
        ]
      },
      "source": {
        "advisory": "GHSA-p7hr-f446-x6qf",
        "discovery": "UNKNOWN"
      }
    },
    "gitlab.com": {
      "advisories": [
        {
          "affected_range": "<2.7.2||>=2.8.0,<2.8.1||>=2.9.0,<2.9.1",
          "affected_versions": "All versions before 2.7.2, all versions starting from 2.8.0 before 2.8.1, all versions starting from 2.9.0 before 2.9.1",
          "cwe_ids": [
            "CWE-1035",
            "CWE-617",
            "CWE-937"
          ],
          "date": "2022-09-16",
          "description": "TensorFlow is an open source platform for machine learning. If `tf.sparse.cross` receives an input `separator` that is not a scalar, it gives a `CHECK` fail that can be used to trigger a denial of service attack. We have patched the issue in GitHub commit 83dcb4dbfa094e33db084e97c4d0531a559e0ebf. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue.",
          "fixed_versions": [
            "2.7.2",
            "2.8.1",
            "2.9.1"
          ],
          "identifier": "CVE-2022-35997",
          "identifiers": [
            "GHSA-p7hr-f446-x6qf",
            "CVE-2022-35997"
          ],
          "not_impacted": "All versions starting from 2.7.2 before 2.8.0, all versions starting from 2.8.1 before 2.9.0, all versions starting from 2.9.1",
          "package_slug": "pypi/tensorflow-cpu",
          "pubdate": "2022-09-16",
          "solution": "Upgrade to versions 2.7.2, 2.8.1, 2.9.1 or above.",
          "title": "Reachable Assertion",
          "urls": [
            "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p7hr-f446-x6qf",
            "https://github.com/tensorflow/tensorflow/commit/83dcb4dbfa094e33db084e97c4d0531a559e0ebf",
            "https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0",
            "https://github.com/advisories/GHSA-p7hr-f446-x6qf"
          ],
          "uuid": "494c8241-7b4c-4515-96f9-1d8eaaf14725"
        },
        {
          "affected_range": "<2.7.2||>=2.8.0,<2.8.1||>=2.9.0,<2.9.1",
          "affected_versions": "All versions before 2.7.2, all versions starting from 2.8.0 before 2.8.1, all versions starting from 2.9.0 before 2.9.1",
          "cwe_ids": [
            "CWE-1035",
            "CWE-617",
            "CWE-937"
          ],
          "date": "2022-09-16",
          "description": "TensorFlow is an open source platform for machine learning. If `tf.sparse.cross` receives an input `separator` that is not a scalar, it gives a `CHECK` fail that can be used to trigger a denial of service attack. We have patched the issue in GitHub commit 83dcb4dbfa094e33db084e97c4d0531a559e0ebf. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue.",
          "fixed_versions": [
            "2.7.2",
            "2.9.1",
            "2.8.1"
          ],
          "identifier": "CVE-2022-35997",
          "identifiers": [
            "GHSA-p7hr-f446-x6qf",
            "CVE-2022-35997"
          ],
          "not_impacted": "All versions starting from 2.7.2 before 2.8.0, all versions starting from 2.8.1 before 2.9.0, all versions starting from 2.9.1",
          "package_slug": "pypi/tensorflow-gpu",
          "pubdate": "2022-09-16",
          "solution": "Upgrade to versions 2.7.2, 2.9.1, 2.8.1 or above.",
          "title": "Reachable Assertion",
          "urls": [
            "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p7hr-f446-x6qf",
            "https://github.com/tensorflow/tensorflow/commit/83dcb4dbfa094e33db084e97c4d0531a559e0ebf",
            "https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0",
            "https://github.com/advisories/GHSA-p7hr-f446-x6qf"
          ],
          "uuid": "66f70228-35dc-4dc8-a734-10dc8665ef9c"
        },
        {
          "affected_range": "<2.7.2||>=2.8.0,<2.8.1||>=2.9.0,<2.9.1||==2.10",
          "affected_versions": "All versions before 2.7.2, all versions starting from 2.8.0 before 2.8.1, all versions starting from 2.9.0 before 2.9.1, version 2.10",
          "cvss_v3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "cwe_ids": [
            "CWE-1035",
            "CWE-617",
            "CWE-937"
          ],
          "date": "2022-09-20",
          "description": "TensorFlow is an open source platform for machine learning. If `tf.sparse.cross` receives an input `separator` that is not a scalar, it gives a `CHECK` fail that can be used to trigger a denial of service attack. We have patched the issue in GitHub commit 83dcb4dbfa094e33db084e97c4d0531a559e0ebf. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue.",
          "fixed_versions": [
            "2.7.2",
            "2.8.1",
            "2.9.1"
          ],
          "identifier": "CVE-2022-35997",
          "identifiers": [
            "CVE-2022-35997",
            "GHSA-p7hr-f446-x6qf"
          ],
          "not_impacted": "All versions starting from 2.7.2 before 2.8.0, all versions starting from 2.8.1 before 2.9.0, all versions starting from 2.9.1 before 2.10, all versions after 2.10",
          "package_slug": "pypi/tensorflow",
          "pubdate": "2022-09-16",
          "solution": "Upgrade to versions 2.7.2, 2.8.1, 2.9.1 or above.",
          "title": "Reachable Assertion",
          "urls": [
            "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p7hr-f446-x6qf",
            "https://github.com/tensorflow/tensorflow/commit/83dcb4dbfa094e33db084e97c4d0531a559e0ebf",
            "https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0",
            "https://github.com/advisories/GHSA-p7hr-f446-x6qf"
          ],
          "uuid": "005a7635-2897-4df9-b5e9-41926ccf267f"
        }
      ]
    },
    "nvd.nist.gov": {
      "configurations": {
        "CVE_data_version": "4.0",
        "nodes": [
          {
            "children": [],
            "cpe_match": [
              {
                "cpe23Uri": "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*",
                "cpe_name": [],
                "versionEndExcluding": "2.8.1",
                "versionStartIncluding": "2.8.0",
                "vulnerable": true
              },
              {
                "cpe23Uri": "cpe:2.3:a:google:tensorflow:2.10:rc1:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": true
              },
              {
                "cpe23Uri": "cpe:2.3:a:google:tensorflow:2.10:rc2:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": true
              },
              {
                "cpe23Uri": "cpe:2.3:a:google:tensorflow:2.10:rc3:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": true
              },
              {
                "cpe23Uri": "cpe:2.3:a:google:tensorflow:2.10:rc0:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": true
              },
              {
                "cpe23Uri": "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*",
                "cpe_name": [],
                "versionEndExcluding": "2.9.1",
                "versionStartIncluding": "2.9.0",
                "vulnerable": true
              },
              {
                "cpe23Uri": "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*",
                "cpe_name": [],
                "versionEndExcluding": "2.7.2",
                "vulnerable": true
              }
            ],
            "operator": "OR"
          }
        ]
      },
      "cve": {
        "CVE_data_meta": {
          "ASSIGNER": "security-advisories@github.com",
          "ID": "CVE-2022-35997"
        },
        "data_format": "MITRE",
        "data_type": "CVE",
        "data_version": "4.0",
        "description": {
          "description_data": [
            {
              "lang": "en",
              "value": "TensorFlow is an open source platform for machine learning. If `tf.sparse.cross` receives an input `separator` that is not a scalar, it gives a `CHECK` fail that can be used to trigger a denial of service attack. We have patched the issue in GitHub commit 83dcb4dbfa094e33db084e97c4d0531a559e0ebf. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue."
            }
          ]
        },
        "problemtype": {
          "problemtype_data": [
            {
              "description": [
                {
                  "lang": "en",
                  "value": "CWE-617"
                }
              ]
            }
          ]
        },
        "references": {
          "reference_data": [
            {
              "name": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p7hr-f446-x6qf",
              "refsource": "CONFIRM",
              "tags": [
                "Third Party Advisory"
              ],
              "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p7hr-f446-x6qf"
            },
            {
              "name": "https://github.com/tensorflow/tensorflow/commit/83dcb4dbfa094e33db084e97c4d0531a559e0ebf",
              "refsource": "MISC",
              "tags": [
                "Patch",
                "Third Party Advisory"
              ],
              "url": "https://github.com/tensorflow/tensorflow/commit/83dcb4dbfa094e33db084e97c4d0531a559e0ebf"
            }
          ]
        }
      },
      "impact": {
        "baseMetricV3": {
          "cvssV3": {
            "attackComplexity": "LOW",
            "attackVector": "NETWORK",
            "availabilityImpact": "HIGH",
            "baseScore": 7.5,
            "baseSeverity": "HIGH",
            "confidentialityImpact": "NONE",
            "integrityImpact": "NONE",
            "privilegesRequired": "NONE",
            "scope": "UNCHANGED",
            "userInteraction": "NONE",
            "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "version": "3.1"
          },
          "exploitabilityScore": 3.9,
          "impactScore": 3.6
        }
      },
      "lastModifiedDate": "2022-09-20T14:49Z",
      "publishedDate": "2022-09-16T23:15Z"
    }
  }
}