{
    "GSD": {
        "alias": "CVE-2021-41200",
        "description": "TensorFlow is an open source platform for machine learning. In affected versions if `tf.summary.create_file_writer` is called with non-scalar arguments code crashes due to a `CHECK`-fail. The fix will be included in TensorFlow 2.7.0. We will also cherrypick this commit on TensorFlow 2.6.1, TensorFlow 2.5.2, and TensorFlow 2.4.4, as these are also affected and still in supported range.",
        "id": "GSD-2021-41200",
        "references": [
            "https://www.suse.com/security/cve/CVE-2021-41200.html",
            "https://security.archlinux.org/CVE-2021-41200"
        ]
    },
    "namespaces": {
        "cve.org": {
            "CVE_data_meta": {
                "ASSIGNER": "security-advisories@github.com",
                "ID": "CVE-2021-41200",
                "STATE": "PUBLIC",
                "TITLE": "Incomplete validation in `tf.summary.create_file_writer`"
            },
            "affects": {
                "vendor": {
                    "vendor_data": [
                        {
                            "product": {
                                "product_data": [
                                    {
                                        "product_name": "tensorflow",
                                        "version": {
                                            "version_data": [
                                                {
                                                    "version_value": ">= 2.6.0, < 2.6.1"
                                                },
                                                {
                                                    "version_value": ">= 2.5.0, < 2.5.2"
                                                },
                                                {
                                                    "version_value": "< 2.4.4"
                                                }
                                            ]
                                        }
                                    }
                                ]
                            },
                            "vendor_name": "tensorflow"
                        }
                    ]
                }
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "eng",
                        "value": "TensorFlow is an open source platform for machine learning. In affected versions if `tf.summary.create_file_writer` is called with non-scalar arguments code crashes due to a `CHECK`-fail. The fix will be included in TensorFlow 2.7.0. We will also cherrypick this commit on TensorFlow 2.6.1, TensorFlow 2.5.2, and TensorFlow 2.4.4, as these are also affected and still in supported range."
                    }
                ]
            },
            "impact": {
                "cvss": {
                    "attackComplexity": "LOW",
                    "attackVector": "LOCAL",
                    "availabilityImpact": "HIGH",
                    "baseScore": 5.5,
                    "baseSeverity": "MEDIUM",
                    "confidentialityImpact": "NONE",
                    "integrityImpact": "NONE",
                    "privilegesRequired": "LOW",
                    "scope": "UNCHANGED",
                    "userInteraction": "NONE",
                    "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                    "version": "3.1"
                }
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": [
                            {
                                "lang": "eng",
                                "value": "CWE-617: Reachable Assertion"
                            }
                        ]
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-gh8h-7j2j-qv4f",
                        "refsource": "CONFIRM",
                        "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-gh8h-7j2j-qv4f"
                    },
                    {
                        "name": "https://github.com/tensorflow/tensorflow/issues/46909",
                        "refsource": "MISC",
                        "url": "https://github.com/tensorflow/tensorflow/issues/46909"
                    },
                    {
                        "name": "https://github.com/tensorflow/tensorflow/commit/874bda09e6702cd50bac90b453b50bcc65b2769e",
                        "refsource": "MISC",
                        "url": "https://github.com/tensorflow/tensorflow/commit/874bda09e6702cd50bac90b453b50bcc65b2769e"
                    }
                ]
            },
            "source": {
                "advisory": "GHSA-gh8h-7j2j-qv4f",
                "discovery": "UNKNOWN"
            }
        },
        "gitlab.com": {
            "advisories": [
                {
                    "affected_range": ">=2.6.0,<2.6.1||>=2.5.0,<2.5.2||<2.4.4",
                    "affected_versions": "All versions starting from 2.6.0 before 2.6.1, all versions starting from 2.5.0 before 2.5.2, all versions before 2.4.4",
                    "cvss_v2": "AV:L/AC:L/Au:N/C:N/I:N/A:P",
                    "cvss_v3": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                    "cwe_ids": [
                        "CWE-1035",
                        "CWE-617",
                        "CWE-937"
                    ],
                    "date": "2021-11-10",
                    "description": "TensorFlow is an open source platform for machine learning. In affected versions if `tf.summary.create_file_writer` is called with non-scalar arguments code crashes due to a `CHECK`-fail. The fix will be included in TensorFlow 2.7.0. We will also cherrypick this commit on TensorFlow 2.6.1, TensorFlow 2.5.2, and TensorFlow 2.4.4, as these are also affected and still in supported range.",
                    "fixed_versions": [
                        "2.6.1",
                        "2.4.4",
                        "2.4.4"
                    ],
                    "identifier": "CVE-2021-41200",
                    "identifiers": [
                        "GHSA-gh8h-7j2j-qv4f",
                        "CVE-2021-41200"
                    ],
                    "not_impacted": "All versions before 2.6.0, all versions starting from 2.6.1, all versions before 2.5.0, all versions starting from 2.4.4 before 2.5.2",
                    "package_slug": "pypi/tensorflow-cpu",
                    "pubdate": "2021-11-10",
                    "solution": "Upgrade to versions 2.6.1, 2.4.4, 2.4.4 or above.",
                    "title": "Reachable Assertion",
                    "urls": [
                        "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-gh8h-7j2j-qv4f",
                        "https://nvd.nist.gov/vuln/detail/CVE-2021-41200",
                        "https://github.com/tensorflow/tensorflow/issues/46909",
                        "https://github.com/tensorflow/tensorflow/commit/874bda09e6702cd50bac90b453b50bcc65b2769e",
                        "https://github.com/advisories/GHSA-gh8h-7j2j-qv4f"
                    ],
                    "uuid": "d1305914-2e14-49b8-9ee0-b12387b61af4"
                },
                {
                    "affected_range": ">=2.6.0,<2.6.1||>=2.5.0,<2.5.2||<2.4.4",
                    "affected_versions": "All versions starting from 2.6.0 before 2.6.1, all versions starting from 2.5.0 before 2.5.2, all versions before 2.4.4",
                    "cvss_v2": "AV:L/AC:L/Au:N/C:N/I:N/A:P",
                    "cvss_v3": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                    "cwe_ids": [
                        "CWE-1035",
                        "CWE-617",
                        "CWE-937"
                    ],
                    "date": "2021-11-10",
                    "description": "TensorFlow is an open source platform for machine learning. In affected versions if `tf.summary.create_file_writer` is called with non-scalar arguments code crashes due to a `CHECK`-fail. The fix will be included in TensorFlow 2.7.0. We will also cherrypick this commit on TensorFlow 2.6.1, TensorFlow 2.5.2, and TensorFlow 2.4.4, as these are also affected and still in supported range.",
                    "fixed_versions": [
                        "2.6.1",
                        "2.4.4",
                        "2.4.4"
                    ],
                    "identifier": "CVE-2021-41200",
                    "identifiers": [
                        "GHSA-gh8h-7j2j-qv4f",
                        "CVE-2021-41200"
                    ],
                    "not_impacted": "All versions before 2.6.0, all versions starting from 2.6.1, all versions before 2.5.0, all versions starting from 2.4.4 before 2.5.2",
                    "package_slug": "pypi/tensorflow-gpu",
                    "pubdate": "2021-11-10",
                    "solution": "Upgrade to versions 2.6.1, 2.4.4, 2.4.4 or above.",
                    "title": "Reachable Assertion",
                    "urls": [
                        "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-gh8h-7j2j-qv4f",
                        "https://nvd.nist.gov/vuln/detail/CVE-2021-41200",
                        "https://github.com/tensorflow/tensorflow/issues/46909",
                        "https://github.com/tensorflow/tensorflow/commit/874bda09e6702cd50bac90b453b50bcc65b2769e",
                        "https://github.com/advisories/GHSA-gh8h-7j2j-qv4f"
                    ],
                    "uuid": "74fb0b40-f03e-4bef-bb16-12921f276785"
                },
                {
                    "affected_range": "<2.4.4||>=2.5.0,<2.5.2||==2.6.0",
                    "affected_versions": "All versions before 2.4.4, all versions starting from 2.5.0 before 2.5.2, version 2.6.0",
                    "cvss_v2": "AV:L/AC:L/Au:N/C:N/I:N/A:P",
                    "cvss_v3": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                    "cwe_ids": [
                        "CWE-1035",
                        "CWE-617",
                        "CWE-937"
                    ],
                    "date": "2021-11-09",
                    "description": "TensorFlow is an open source platform for machine learning. The fix will be included in TensorFlow We will also cherrypick this commit on TensorFlow, TensorFlow, and TensorFlow, as these are also affected and still in supported range.",
                    "fixed_versions": [
                        "2.4.4",
                        "2.5.2",
                        "2.6.1"
                    ],
                    "identifier": "CVE-2021-41200",
                    "identifiers": [
                        "CVE-2021-41200",
                        "GHSA-gh8h-7j2j-qv4f"
                    ],
                    "not_impacted": "All versions starting from 2.4.4 before 2.5.0, all versions starting from 2.5.2 before 2.6.0, all versions after 2.6.0",
                    "package_slug": "pypi/tensorflow",
                    "pubdate": "2021-11-05",
                    "solution": "Upgrade to versions 2.4.4, 2.5.2, 2.6.1 or above.",
                    "title": "Reachable Assertion",
                    "urls": [
                        "https://nvd.nist.gov/vuln/detail/CVE-2021-41200",
                        "https://github.com/tensorflow/tensorflow/issues/46909",
                        "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-gh8h-7j2j-qv4f",
                        "https://github.com/tensorflow/tensorflow/commit/874bda09e6702cd50bac90b453b50bcc65b2769e"
                    ],
                    "uuid": "11197567-74c2-455e-80f9-c3f51e8e25d4"
                }
            ]
        },
        "nvd.nist.gov": {
            "configurations": {
                "CVE_data_version": "4.0",
                "nodes": [
                    {
                        "children": [],
                        "cpe_match": [
                            {
                                "cpe23Uri": "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*",
                                "cpe_name": [],
                                "versionEndExcluding": "2.4.4",
                                "vulnerable": true
                            },
                            {
                                "cpe23Uri": "cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*",
                                "cpe_name": [],
                                "versionEndExcluding": "2.5.2",
                                "versionStartIncluding": "2.5.0",
                                "vulnerable": true
                            },
                            {
                                "cpe23Uri": "cpe:2.3:a:google:tensorflow:2.6.0:*:*:*:*:*:*:*",
                                "cpe_name": [],
                                "vulnerable": true
                            }
                        ],
                        "operator": "OR"
                    }
                ]
            },
            "cve": {
                "CVE_data_meta": {
                    "ASSIGNER": "security-advisories@github.com",
                    "ID": "CVE-2021-41200"
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "en",
                            "value": "TensorFlow is an open source platform for machine learning. In affected versions if `tf.summary.create_file_writer` is called with non-scalar arguments code crashes due to a `CHECK`-fail. The fix will be included in TensorFlow 2.7.0. We will also cherrypick this commit on TensorFlow 2.6.1, TensorFlow 2.5.2, and TensorFlow 2.4.4, as these are also affected and still in supported range."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "en",
                                    "value": "CWE-617"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://github.com/tensorflow/tensorflow/issues/46909",
                            "refsource": "MISC",
                            "tags": [
                                "Exploit",
                                "Third Party Advisory"
                            ],
                            "url": "https://github.com/tensorflow/tensorflow/issues/46909"
                        },
                        {
                            "name": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-gh8h-7j2j-qv4f",
                            "refsource": "CONFIRM",
                            "tags": [
                                "Exploit",
                                "Third Party Advisory"
                            ],
                            "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-gh8h-7j2j-qv4f"
                        },
                        {
                            "name": "https://github.com/tensorflow/tensorflow/commit/874bda09e6702cd50bac90b453b50bcc65b2769e",
                            "refsource": "MISC",
                            "tags": [
                                "Patch",
                                "Third Party Advisory"
                            ],
                            "url": "https://github.com/tensorflow/tensorflow/commit/874bda09e6702cd50bac90b453b50bcc65b2769e"
                        }
                    ]
                }
            },
            "impact": {
                "baseMetricV2": {
                    "acInsufInfo": false,
                    "cvssV2": {
                        "accessComplexity": "LOW",
                        "accessVector": "LOCAL",
                        "authentication": "NONE",
                        "availabilityImpact": "PARTIAL",
                        "baseScore": 2.1,
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "vectorString": "AV:L/AC:L/Au:N/C:N/I:N/A:P",
                        "version": "2.0"
                    },
                    "exploitabilityScore": 3.9,
                    "impactScore": 2.9,
                    "obtainAllPrivilege": false,
                    "obtainOtherPrivilege": false,
                    "obtainUserPrivilege": false,
                    "severity": "LOW",
                    "userInteractionRequired": false
                },
                "baseMetricV3": {
                    "cvssV3": {
                        "attackComplexity": "LOW",
                        "attackVector": "LOCAL",
                        "availabilityImpact": "HIGH",
                        "baseScore": 5.5,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "LOW",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                        "version": "3.1"
                    },
                    "exploitabilityScore": 1.8,
                    "impactScore": 3.6
                }
            },
            "lastModifiedDate": "2021-11-09T17:40Z",
            "publishedDate": "2021-11-05T20:15Z"
        }
    }
}